openapi: 3.0.0
info:
  title: MyLab.Notifier API
  version: '1'
tags:
  - name: Contacts
  - name: Subjects
servers:
- url: http://base.addr/v1
paths:
  '/contacts/by-subject/{subject_id}':
    
    parameters:
    - $ref: '#/components/parameters/SubjectId'
    
    post:
      tags:
      - Contacts
      summary: Adds new contact for subject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactContent'
      responses:
        '200':
          description: Successfully created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ContactId'
        '400':
          description: Bad request
          
    get:
      tags:
      - Contacts
      summary: Get all subject contacts
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
      
  '/contacts/{contact_id}':
    
    parameters:
      - $ref: '#/components/parameters/ContactId'
      
    delete:
      tags:
      - Contacts
      summary: Delete contact
      responses:
        '200':
          description: Success
          
    get:
      tags:
      - Contacts
      summary: Get contact
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        '404':
          description: Contact not found
                
  '/subjects/{subject_id}/topics/{topic_id}':
    
    parameters:
      - $ref: '#/components/parameters/SubjectId'
      - $ref: '#/components/parameters/TopicId'
      
    put:
      tags: 
      - Subjects
      summary: Binds subject to topic
      responses:
        '200':
          description: Successfully binded
          
    delete:
      tags: 
      - Subjects
      summary: Unbbinds subject to topic
      responses:
        '200':
          description: Successfully unbinded
          
  '/subjects/{subject_id}/topics':
          
    parameters:
      - $ref: '#/components/parameters/SubjectId'
          
    get:
      tags: 
      - Subjects
      summary: Gets subject's topics
      responses:
        '200':
          description: Subject's topics
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/TopicList'
      
  
components:
  parameters:
  
    SubjectId:
      in: path
      required: true
      name: subject_id
      description: Subject identifier
      schema:
        $ref: '#/components/schemas/SubjectId'
        
    ContactId:
      in: path
      required: true
      name: contact_id
      description: Contact unique identifier
      schema:
        $ref: '#/components/schemas/ContactId'
        
    TopicId:
      in: path
      required: true
      name: topic_id
      description: Topic unique identifier
      schema:
        type: string
        example: some-topic
  
  schemas:   
  
    TopicList:
      type: array
      items: 
        type: string
      description: Contains topic list
      example:
      - special-topic
      - another-topic
    
    Contact:
      allOf:
      - $ref: '#/components/schemas/ContactContent'
      - type: object
        description: Contact
        properties:
          id:
            $ref: '#/components/schemas/ContactId'
        required:
        - id
        
    ContactContent:
      type: object
      description: Contact content
      properties:
        value: 
          type: string
          description: Contact value
          example: blabla@host.com
        channelId:
          $ref: '#/components/schemas/ChannelId'
        labels:
          $ref: '#/components/schemas/ContactLabels'
      required: 
      - value
      - channelId
    
    ContactLabels:
      type: object 
      description: Key-value labels
      additionalProperties: true
      example:
        user_id: ololo123
        
    ContactId:
      type: integer
      format: Int32
      description: Contact identifier
      example: 3882
      
    SubjectId:
      type: string
      description: Subject identifier
      example: e37179bc3c2245e0b138cc3ad6002212
    
    ChannelId:
      type: string
      description: Channel identifier
      enum:
      - webpush
      - email